language: node_js
node_js:
  - "20.15"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g yarn

install:
  - yarn install

script:
  - yarn run build

# Optional: You can add stages for testing if required
# stages:
#   - name: test
#     script: yarn test

notifications:
  email:
    recipients:
      - your-email@example.com
    on_success: always
    on_failure: always
